---
- hosts: all
  gather_facts: yes
  roles:
    - role: user
    - role: nginx
    - role: ulimit

  pre_tasks:
    - name: update apt cache if needed
      become: yes
      apt:
        update_cache=yes
        cache_valid_time=3600