---
- hosts: nginx
  gather_facts: yes
  roles:
    - nginx
    - user

  pre_tasks:
    - name: update apt cache if needed
      become: yes
      apt:
        update_cache=yes
        cache_valid_time=3600